# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
	# Box name & download source
	config.vm.box = "Jekyll box 2"
	config.vm.box_url = "http://files.vagrantup.com/precise32.box"

	# Network
	config.vm.network "forwarded_port", host: 4080, guest: 80, auto_correct:true
	config.vm.synced_folder "../", "/jekyll"
	
	 # Fix DNS resolve issue + add juice
	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--memory", "4096"]
		vb.customize ["modifyvm", :id, "--cpus", "4"]   
		vb.customize ["modifyvm", :id, "--ioapic", "on"]
	end

	# Provisioning
	config.vm.provision :shell, :path => "sysupdate.sh"
	config.vm.provision :shell, :path => "rvminstall.sh", :privileged => false
	config.vm.provision :shell, :path => "bootstrap.sh"

end